volumes:
  pg_data:
  static:

services:
  db:
    platform: linux/amd64
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: stxxxx/taski_backend
    env_file: .env
    volumes:
      - static:/app/collected_static
  frontend:
    image: stxxxx/taski_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
  gateway:
    image: stxxxx/taski_gateway
    env_file: .env
    volumes:
      - static:/staticfiles/
    ports:
      - 8000:80